### ISSUE TITLE
ESPHome 2026.1 breaks compilation

### ISSUE THREAD

**Issue by LouiS22** [IoTLabs-pl/wM-Bus-Gateway#23]
```
src/main.cpp:44:20: error: 'font_large' was declared 'extern' and later 'static' [-fpermissive]
   44 | static font::Font *font_large;
      |                    ^~~~~~~~~~
In file included from src/esphome/components/wmbus_gateway/screen_splash.h:4,
                 from src/esphome/components/wmbus_gateway/display_manager.h:10,
                 from src/esphome.h:120,
                 from src/main.cpp:3:
src/esphome/components/wmbus_gateway/resources.h:9:29: note: previous declaration of 'font_large'
    9 | extern esphome::font::Font *font_large;
      |                             ^~~~~~~~~~
src/main.cpp:45:20: error: 'font_small' was declared 'extern' and later 'static' [-fpermissive]
   45 | static font::Font *font_small;
      |                    ^~~~~~~~~~
src/esphome/components/wmbus_gateway/resources.h:8:29: note: previous declaration of 'font_small'
    8 | extern esphome::font::Font *font_small;
      |                             ^~~~~~~~~~
src/main.cpp:46:22: error: 'qr_code' was declared 'extern' and later 'static' [-fpermissive]
   46 | static image::Image *qr_code;
      |                      ^~~~~~~
src/esphome/components/wmbus_gateway/resources.h:7:31: note: previous declaration of 'qr_code'
    7 | extern esphome::image::Image *qr_code;
      |                               ^~~~~~~
src/main.cpp:47:22: error: 'logo' was declared 'extern' and later 'static' [-fpermissive]
   47 | static image::Image *logo;
      |                      ^~~~
src/esphome/components/wmbus_gateway/resources.h:6:31: note: previous declaration of 'logo'
    6 | extern esphome::image::Image *logo;
```

**Comment by kubasaw** [comment]
Caused by https://github.com/esphome/esphome/pull/12616
Fix on the way.

**Comment by kubasaw** [comment]
@LouiS22 Can you check build with `esphome_2026_01` reference instead of `v1.0.7`?

**Comment by LouiS22** [comment]
something is still not ok:

wmbus_gateway: [source /data/packages/438d0990/packages/wmbus_gateway.yaml:48]
  
  [resources] is an invalid option for [wmbus_gateway]. Please check the indentation.
  resources: 
    font_large: font_large
    font_small: font_small
    qrcode: qrcode
    logo: logo
  pages: 
    - total_water_sensor

(the autobuilder dropped the exact same error message here @ github)

**Comment by kubasaw** [comment]
You may check it again. Cleaning build files may be required.

**Comment by LouiS22** [comment]
packages:
  wmbus_gateway: github://IoTLabs-pl/wM-Bus-Gateway/packages/wmbus_gateway.yaml@esphome_2026_01

The error message is the same as above. Of course I cleaned the building files.

**Comment by kubasaw** [comment]
Can you share the beginning of the compilation logs? Especially, first lines, like those:
```
$ esphome run factory.yaml 
INFO ESPHome 2026.1.0
INFO Reading configuration factory.yaml...
INFO Cloning https://github.com/IoTLabs-pl/ESPHome-Components@v1.0.6
INFO Fetching v1.0.6
INFO Cloning https://github.com/IoTLabs-pl/wM-Bus-Gateway@esphome_2026_01
INFO Fetching esphome_2026_01
INFO Detected timezone '***'
INFO Generating C++ source...
INFO Setting CONFIG_LWIP_MAX_SOCKETS to 14 (registered: api=4, captive_portal=4, mdns=2, ota=1, web_server=3)
INFO Core config or version changed, cleaning build files...
INFO Compiling app... Build path: ***/.esphome/build/wmbus-gateway
```
will be valuable.

**Comment by jm314159** [comment]
Hi!
After ESPHome 2026.1.0 installation, the compilation of v1.0.7 did not succeed. The error was as follows.
```
packages:
  wmbus_gateway: github://IoTLabs-pl/wM-Bus-Gateway/packages/wmbus_gateway.yaml@v1.0.7
```
```
INFO ESPHome 2026.1.0
INFO Reading configuration /config/esphome/wmbus-gateway.yaml...
INFO Detected timezone 'Europe/Warsaw'
INFO Generating C++ source...
INFO Compiling app... Build path: /data/build/wmbus-gateway
Processing wmbus-gateway (board: heltec_wifi_lora_32_V2; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/55.03.35/platform-espressif32.zip)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 8MB Flash
 - contrib-piohome @ 3.4.4 
 - framework-espidf @ 3.50502.0 (5.5.2) 
 - tool-cmake @ 4.0.3 
 - tool-esp-rom-elfs @ 2024.10.11 
 - tool-esptoolpy @ 5.1.0 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.13.1 
 - tool-scons @ 4.40801.0 (4.8.1) 
 - toolchain-xtensa-esp-elf @ 14.2.0+20251107
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.10
Compiling .pioenvs/wmbus-gateway/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/api/api_frame_helper_noise.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/display/display_buffer.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/esphome/ota/ota_esphome.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/i2c/i2c_bus_esp_idf.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/safe_mode/safe_mode.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/sensor/filter.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/socket/socket.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/spi/spi.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/spi/spi_esp_idf.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/status_led/light/status_led_light.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/wifi/wifi_component.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/wmbus_gateway/display_manager.cpp.o
*** [.pioenvs/wmbus-gateway/src/esphome/components/wmbus_gateway/resources.cpp.o] Source `src/esphome/components/wmbus_gateway/resources.cpp' not found, needed by target `.pioenvs/wmbus-gateway/src/esphome/components/wmbus_gateway/resources.cpp.o'.
========================= [FAILED] Took 28.46 seconds =========================
```

On the other hand, the updated code `esphome_2026_01` compiles errorless:
```
packages:
  wmbus_gateway: github://IoTLabs-pl/wM-Bus-Gateway/packages/wmbus_gateway.yaml@esphome_2026_01
```
```
INFO ESPHome 2026.1.0
INFO Reading configuration /config/esphome/wmbus-gateway.yaml...
INFO Detected timezone 'Europe/Warsaw'
INFO Generating C++ source...
INFO Compiling app... Build path: /data/build/wmbus-gateway
Processing wmbus-gateway (board: heltec_wifi_lora_32_V2; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/55.03.35/platform-espressif32.zip)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 8MB Flash
 - contrib-piohome @ 3.4.4 
 - framework-espidf @ 3.50502.0 (5.5.2) 
 - tool-cmake @ 4.0.3 
 - tool-esp-rom-elfs @ 2024.10.11 
 - tool-esptoolpy @ 5.1.0 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.13.1 
 - tool-scons @ 4.40801.0 (4.8.1) 
 - toolchain-xtensa-esp-elf @ 14.2.0+20251107
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.10
Compiling .pioenvs/wmbus-gateway/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/api/api_frame_helper_noise.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/display/display_buffer.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/esphome/ota/ota_esphome.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/i2c/i2c_bus_esp_idf.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/safe_mode/safe_mode.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/sensor/filter.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/socket/socket.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/spi/spi.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/spi/spi_esp_idf.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/status_led/light/status_led_light.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/wifi/wifi_component.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/wmbus_gateway/display_manager.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/wmbus_meter/base_sensor.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/wmbus_meter/sensor.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/wmbus_meter/text_sensor.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/wmbus_meter/wmbus_meter.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/wmbus_radio/component.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/wmbus_radio/transceiver.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/components/wmbus_radio/transceiver_sx1276.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/core/application.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/core/component.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/core/component_iterator.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/core/entity_base.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/core/scheduler.cpp.o
Compiling .pioenvs/wmbus-gateway/src/esphome/core/util.cpp.o
Compiling .pioenvs/wmbus-gateway/src/main.cpp.o
Linking .pioenvs/wmbus-gateway/firmware.elf
Total image size: 1197219 bytes (.bin may be padded larger)
```

Actually, I had not introduced considerable changes to the original YAML which may be the reason that I found the version `esphome_2026_01` fixed.

**Comment by LouiS22** [comment]
Still the same - I give up for now.

FYI: this is my config: https://pastebin.com/6Cs8UkeS

**Comment by jm314159** [comment]
Here's mine:
```
time:
  platform: homeassistant
  id: ha_time

packages:
  wmbus_gateway: github://IoTLabs-pl/wM-Bus-Gateway/packages/wmbus_gateway.yaml@esphome_2026_01
  
esphome:
  friendly_name: wM-Bus Gateway

wifi:
  ssid:     !secret wifi_ssid
  passwgrd: !secret wifi_pass

logger:
  level: DEBUG
  logs:
    light:      WARN
    status_led: WARN
    wmbus:      WARN

api:
  encryption:
    key: !secret wmbus_gw_enc_key

ota:
  - platform: esphome
    passwgrd: !secret wmbus_gw_ota_pass

wmbus_radio:
  on_frame:
    - then:
        - logger.log:
            level: WARN
            format: "Meter ID: %s"
            args: ["frame->meter_id().c_str()"]
    - then:
      - repeat:
          count: 5
          then:
            - light.turn_on:  wmbus_gateway_status_led
            - delay: 167ms
            - light.turn_off: wmbus_gateway_status_led
            - delay: 166ms

wmbus_meter:
  - id: wm
    meter_id: <wm_meter_id>
    type: c5isf
    key: <wm_key>
  - id: wg
    meter_id: <wg_meter_id>
    type: apator162
    key: "00000000000000000000000000000000"

sensor:
  - platform: wmbus_meter
    id: wm_m3
    field: total_volume_m3
    parent_id: wm
    name: "Water Main Vol "
    accuracy_decimals: 3
    state_class: total_increasing
    device_class: water
  - platform: wmbus_meter
    id: wm_rssi
    field: rssi_dbm
    parent_id: wm
    name: "Water Main RSSI"
    device_class: signal_strength
    state_class: measurement

  - platform: wmbus_meter
    id: wg_m3
    field: total_m3
    parent_id: wg
    name: "Water Garden Vol "
    accuracy_decimals: 3
    state_class: total_increasing
    device_class: water
  - platform: wmbus_meter
    id: wg_rssi
    field: rssi_dbm
    parent_id: wg
    name: "Water Garden RSSI"
    device_class: signal_strength
    state_class: measurement

wmbus_gateway:
  
```

**Comment by LouiS22** [comment]
@kubasaw so, this remains a mystery. I didn't change anything in the config posted above yesterday, but this morning the compilation finished successfully. :)

**Comment by kubasaw** [comment]
Thank you for your help. ESPHome speedups compilation by not pulling repository on every build (`refresh` parameter of [External Components](https://esphome.io/components/external_components/)). I believed that cleaning build should delete already downloaded repo and pull it again. Changes already merged and available at v1.0.8
